//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.ActionAnnotations = new HashSet<ActionAnnotation>();
            this.ActionBies = new HashSet<ActionBy>();
            this.ActionDirectives = new HashSet<ActionDirective>();
            this.ActionExtensionPropertyValues = new HashSet<ActionExtensionPropertyValue>();
            this.EquipmentUseds = new HashSet<EquipmentUsed>();
            this.FeatureActions = new HashSet<FeatureAction>();
            this.RelatedActions = new HashSet<RelatedAction>();
            this.RelatedActions1 = new HashSet<RelatedAction>();
            this.Simulations = new HashSet<Simulation>();
        }
    
        public int ActionID { get; set; }
        public string ActionTypeCV { get; set; }
        public int MethodID { get; set; }
        public System.DateTime BeginDateTime { get; set; }
        public int BeginDateTimeUTCOffset { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> EndDateTimeUTCOffset { get; set; }
        public string ActionDescription { get; set; }
        public string ActionFileLink { get; set; }
    
        public virtual ICollection<ActionAnnotation> ActionAnnotations { get; set; }
        public virtual ICollection<ActionBy> ActionBies { get; set; }
        public virtual ICollection<ActionDirective> ActionDirectives { get; set; }
        public virtual ICollection<ActionExtensionPropertyValue> ActionExtensionPropertyValues { get; set; }
        public virtual Method Method { get; set; }
        public virtual CalibrationAction CalibrationAction { get; set; }
        public virtual ICollection<EquipmentUsed> EquipmentUseds { get; set; }
        public virtual ICollection<FeatureAction> FeatureActions { get; set; }
        public virtual MaintenanceAction MaintenanceAction { get; set; }
        public virtual ICollection<RelatedAction> RelatedActions { get; set; }
        public virtual ICollection<RelatedAction> RelatedActions1 { get; set; }
        public virtual ICollection<Simulation> Simulations { get; set; }
    }
}
