//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionExtensionPropertyValue
    {
        public int BridgeID { get; set; }
        public int ActionID { get; set; }
        public int PropertyID { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual ExtensionProperty ExtensionProperty { get; set; }
    }
}
