//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affiliation
    {
        public Affiliation()
        {
            this.ActionBies = new HashSet<ActionBy>();
            this.DataloggerProgramFiles = new HashSet<DataloggerProgramFile>();
            this.ModelAffiliations = new HashSet<ModelAffiliation>();
        }
    
        public int AffiliationID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<bool> IsPrimaryOrganizationContact { get; set; }
        public System.DateTime AffiliationStartDate { get; set; }
        public Nullable<System.DateTime> AffiliationEndDate { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryAddress { get; set; }
        public string PersonLink { get; set; }
    
        public virtual ICollection<ActionBy> ActionBies { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<DataloggerProgramFile> DataloggerProgramFiles { get; set; }
        public virtual ICollection<ModelAffiliation> ModelAffiliations { get; set; }
    }
}
