//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationAction
    {
        public CalibrationAction()
        {
            this.CalibrationReferenceEquipments = new HashSet<CalibrationReferenceEquipment>();
            this.CalibrationStandards = new HashSet<CalibrationStandard>();
        }
    
        public int ActionID { get; set; }
        public Nullable<double> CalibrationCheckValue { get; set; }
        public int InstrumentOutputVariableID { get; set; }
        public string CalibrationEquation { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual InstrumentOutputVariable InstrumentOutputVariable { get; set; }
        public virtual ICollection<CalibrationReferenceEquipment> CalibrationReferenceEquipments { get; set; }
        public virtual ICollection<CalibrationStandard> CalibrationStandards { get; set; }
    }
}
