//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoricalResultValue
    {
        public CategoricalResultValue()
        {
            this.CategoricalResultValueAnnotations = new HashSet<CategoricalResultValueAnnotation>();
        }
    
        public long ValueID { get; set; }
        public long ResultID { get; set; }
        public string DataValue { get; set; }
        public System.DateTime ValueDateTime { get; set; }
        public int ValueDateTimeUTCOffset { get; set; }
    
        public virtual CategoricalResult CategoricalResult { get; set; }
        public virtual ICollection<CategoricalResultValueAnnotation> CategoricalResultValueAnnotations { get; set; }
    }
}
