//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citation
    {
        public Citation()
        {
            this.Annotations = new HashSet<Annotation>();
            this.AuthorLists = new HashSet<AuthorList>();
            this.CitationExtensionPropertyValues = new HashSet<CitationExtensionPropertyValue>();
            this.CitationExternalIdentifiers = new HashSet<CitationExternalIdentifier>();
            this.DataSetCitations = new HashSet<DataSetCitation>();
            this.MethodCitations = new HashSet<MethodCitation>();
            this.ReferenceMaterialValues = new HashSet<ReferenceMaterialValue>();
            this.RelatedCitations = new HashSet<RelatedCitation>();
            this.RelatedCitations1 = new HashSet<RelatedCitation>();
        }
    
        public int CitationID { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public int PublicationYear { get; set; }
        public string CitationLink { get; set; }
    
        public virtual ICollection<Annotation> Annotations { get; set; }
        public virtual ICollection<AuthorList> AuthorLists { get; set; }
        public virtual ICollection<CitationExtensionPropertyValue> CitationExtensionPropertyValues { get; set; }
        public virtual ICollection<CitationExternalIdentifier> CitationExternalIdentifiers { get; set; }
        public virtual ICollection<DataSetCitation> DataSetCitations { get; set; }
        public virtual ICollection<MethodCitation> MethodCitations { get; set; }
        public virtual ICollection<ReferenceMaterialValue> ReferenceMaterialValues { get; set; }
        public virtual ICollection<RelatedCitation> RelatedCitations { get; set; }
        public virtual ICollection<RelatedCitation> RelatedCitations1 { get; set; }
    }
}
