//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVTerm
    {
        public int TermID { get; set; }
        public string Term { get; set; }
        public string Definition { get; set; }
        public string ODMVocabulary { get; set; }
        public string SourceVocabulary { get; set; }
    }
}
