//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataloggerFileColumn
    {
        public int DataloggerFileColumnID { get; set; }
        public Nullable<long> ResultID { get; set; }
        public int DataLoggerFileID { get; set; }
        public int InstrumentOutputVariableID { get; set; }
        public string ColumnLabel { get; set; }
        public string ColumnDescription { get; set; }
        public string MeasurementEquation { get; set; }
        public Nullable<double> ScanInterval { get; set; }
        public Nullable<int> ScanIntervalUnitsID { get; set; }
        public Nullable<double> RecordingInterval { get; set; }
        public Nullable<int> RecordingIntervalUnitsID { get; set; }
        public string AggregationStatisticCV { get; set; }
    
        public virtual DataLoggerFile DataLoggerFile { get; set; }
        public virtual InstrumentOutputVariable InstrumentOutputVariable { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Result Result { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
