//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataQuality
    {
        public DataQuality()
        {
            this.ResultsDataQualities = new HashSet<ResultsDataQuality>();
        }
    
        public int DataQualityID { get; set; }
        public string DataQualityTypeCV { get; set; }
        public string DataQualityCode { get; set; }
        public Nullable<double> DataQualityValue { get; set; }
        public Nullable<int> DataQualityValueUnitsID { get; set; }
        public string DataQualityDescription { get; set; }
        public string DataQualityLink { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ResultsDataQuality> ResultsDataQualities { get; set; }
    }
}
