//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directive
    {
        public Directive()
        {
            this.ActionDirectives = new HashSet<ActionDirective>();
        }
    
        public int DirectiveID { get; set; }
        public string DirectiveTypeCV { get; set; }
        public string DirectiveDescription { get; set; }
    
        public virtual ICollection<ActionDirective> ActionDirectives { get; set; }
    }
}
