//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentModel
    {
        public EquipmentModel()
        {
            this.Equipments = new HashSet<Equipment>();
            this.InstrumentOutputVariables = new HashSet<InstrumentOutputVariable>();
        }
    
        public int EquipmentModelID { get; set; }
        public int ModelManufacturerID { get; set; }
        public string ModelPartNumber { get; set; }
        public string ModelName { get; set; }
        public string ModelDescription { get; set; }
        public bool IsInstrument { get; set; }
        public string ModelSpecificationsFileLink { get; set; }
        public string ModelLink { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<InstrumentOutputVariable> InstrumentOutputVariables { get; set; }
    }
}
