//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalIdentifierSystem
    {
        public ExternalIdentifierSystem()
        {
            this.CitationExternalIdentifiers = new HashSet<CitationExternalIdentifier>();
            this.MethodExternalIdentifiers = new HashSet<MethodExternalIdentifier>();
            this.PersonExternalIdentifiers = new HashSet<PersonExternalIdentifier>();
            this.ReferenceMaterialExternalIdentifiers = new HashSet<ReferenceMaterialExternalIdentifier>();
            this.SamplingFeatureExternalIdentifiers = new HashSet<SamplingFeatureExternalIdentifier>();
            this.SpatialReferenceExternalIdentifiers = new HashSet<SpatialReferenceExternalIdentifier>();
            this.TaxonomicClassifierExternalIdentifiers = new HashSet<TaxonomicClassifierExternalIdentifier>();
            this.VariableExternalIdentifiers = new HashSet<VariableExternalIdentifier>();
        }
    
        public int ExternalIdentifierSystemID { get; set; }
        public string ExternalIdentifierSystemName { get; set; }
        public int IdentifierSystemOrganizationID { get; set; }
        public string ExternalIdentifierSystemDescription { get; set; }
        public string ExternalIdentifierSystemURL { get; set; }
    
        public virtual ICollection<CitationExternalIdentifier> CitationExternalIdentifiers { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<MethodExternalIdentifier> MethodExternalIdentifiers { get; set; }
        public virtual ICollection<PersonExternalIdentifier> PersonExternalIdentifiers { get; set; }
        public virtual ICollection<ReferenceMaterialExternalIdentifier> ReferenceMaterialExternalIdentifiers { get; set; }
        public virtual ICollection<SamplingFeatureExternalIdentifier> SamplingFeatureExternalIdentifiers { get; set; }
        public virtual ICollection<SpatialReferenceExternalIdentifier> SpatialReferenceExternalIdentifiers { get; set; }
        public virtual ICollection<TaxonomicClassifierExternalIdentifier> TaxonomicClassifierExternalIdentifiers { get; set; }
        public virtual ICollection<VariableExternalIdentifier> VariableExternalIdentifiers { get; set; }
    }
}
