//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionProperty
    {
        public ExtensionProperty()
        {
            this.ActionExtensionPropertyValues = new HashSet<ActionExtensionPropertyValue>();
            this.CitationExtensionPropertyValues = new HashSet<CitationExtensionPropertyValue>();
            this.MethodExtensionPropertyValues = new HashSet<MethodExtensionPropertyValue>();
            this.ResultExtensionPropertyValues = new HashSet<ResultExtensionPropertyValue>();
            this.SamplingFeatureExtensionPropertyValues = new HashSet<SamplingFeatureExtensionPropertyValue>();
            this.VariableExtensionPropertyValues = new HashSet<VariableExtensionPropertyValue>();
        }
    
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyDescription { get; set; }
        public string PropertyDataTypeCV { get; set; }
        public Nullable<int> PropertyUnitsID { get; set; }
    
        public virtual ICollection<ActionExtensionPropertyValue> ActionExtensionPropertyValues { get; set; }
        public virtual ICollection<CitationExtensionPropertyValue> CitationExtensionPropertyValues { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<MethodExtensionPropertyValue> MethodExtensionPropertyValues { get; set; }
        public virtual ICollection<ResultExtensionPropertyValue> ResultExtensionPropertyValues { get; set; }
        public virtual ICollection<SamplingFeatureExtensionPropertyValue> SamplingFeatureExtensionPropertyValues { get; set; }
        public virtual ICollection<VariableExtensionPropertyValue> VariableExtensionPropertyValues { get; set; }
    }
}
