//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureAction
    {
        public FeatureAction()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int FeatureActionID { get; set; }
        public int SamplingFeatureID { get; set; }
        public int ActionID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual SamplingFeature SamplingFeature { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual SpecimenBatchPostion SpecimenBatchPostion { get; set; }
    }
}
