//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodExternalIdentifier
    {
        public int BridgeID { get; set; }
        public int MethodID { get; set; }
        public int ExternalIdentifierSystemID { get; set; }
        public string MethodExternalIdentifier1 { get; set; }
        public string MethodExternalIdentifierURI { get; set; }
    
        public virtual ExternalIdentifierSystem ExternalIdentifierSystem { get; set; }
        public virtual Method Method { get; set; }
    }
}
