//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Method
    {
        public Method()
        {
            this.Actions = new HashSet<Action>();
            this.InstrumentOutputVariables = new HashSet<InstrumentOutputVariable>();
            this.MethodAnnotations = new HashSet<MethodAnnotation>();
            this.MethodCitations = new HashSet<MethodCitation>();
            this.MethodExtensionPropertyValues = new HashSet<MethodExtensionPropertyValue>();
            this.MethodExternalIdentifiers = new HashSet<MethodExternalIdentifier>();
        }
    
        public int MethodID { get; set; }
        public string MethodTypeCV { get; set; }
        public string MethodCode { get; set; }
        public string MethodName { get; set; }
        public string MethodDescription { get; set; }
        public string MethodLink { get; set; }
        public Nullable<int> OrganizationID { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<InstrumentOutputVariable> InstrumentOutputVariables { get; set; }
        public virtual ICollection<MethodAnnotation> MethodAnnotations { get; set; }
        public virtual ICollection<MethodCitation> MethodCitations { get; set; }
        public virtual ICollection<MethodExtensionPropertyValue> MethodExtensionPropertyValues { get; set; }
        public virtual ICollection<MethodExternalIdentifier> MethodExternalIdentifiers { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
