//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.ModelAffiliations = new HashSet<ModelAffiliation>();
            this.RelatedModels = new HashSet<RelatedModel>();
            this.Simulations = new HashSet<Simulation>();
        }
    
        public int ModelID { get; set; }
        public string ModelCode { get; set; }
        public string ModelName { get; set; }
        public string ModelDescription { get; set; }
        public string Version { get; set; }
        public string ModelLink { get; set; }
    
        public virtual ICollection<ModelAffiliation> ModelAffiliations { get; set; }
        public virtual ICollection<RelatedModel> RelatedModels { get; set; }
        public virtual ICollection<Simulation> Simulations { get; set; }
    }
}
