//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Affiliations = new HashSet<Affiliation>();
            this.Equipments = new HashSet<Equipment>();
            this.EquipmentModels = new HashSet<EquipmentModel>();
            this.ExternalIdentifierSystems = new HashSet<ExternalIdentifierSystem>();
            this.Methods = new HashSet<Method>();
            this.Organizations1 = new HashSet<Organization>();
            this.ReferenceMaterials = new HashSet<ReferenceMaterial>();
        }
    
        public int OrganizationID { get; set; }
        public string OrganizationTypeCV { get; set; }
        public string OrganizationCode { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationDescription { get; set; }
        public string OrganizationLink { get; set; }
        public Nullable<int> ParentOrganizationID { get; set; }
    
        public virtual ICollection<Affiliation> Affiliations { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<EquipmentModel> EquipmentModels { get; set; }
        public virtual ICollection<ExternalIdentifierSystem> ExternalIdentifierSystems { get; set; }
        public virtual ICollection<Method> Methods { get; set; }
        public virtual ICollection<Organization> Organizations1 { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual ICollection<ReferenceMaterial> ReferenceMaterials { get; set; }
    }
}
