//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Affiliations = new HashSet<Affiliation>();
            this.Annotations = new HashSet<Annotation>();
            this.AuthorLists = new HashSet<AuthorList>();
            this.Equipments = new HashSet<Equipment>();
            this.PersonExternalIdentifiers = new HashSet<PersonExternalIdentifier>();
        }
    
        public int PersonID { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonMiddleName { get; set; }
        public string PersonLastName { get; set; }
    
        public virtual ICollection<Affiliation> Affiliations { get; set; }
        public virtual ICollection<Annotation> Annotations { get; set; }
        public virtual ICollection<AuthorList> AuthorLists { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<PersonExternalIdentifier> PersonExternalIdentifiers { get; set; }
    }
}
