//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessingLevel
    {
        public ProcessingLevel()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int ProcessingLevelID { get; set; }
        public string ProcessingLevelCode { get; set; }
        public string Definition { get; set; }
        public string Explanation { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
    }
}
