//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceMaterialValue
    {
        public ReferenceMaterialValue()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int ReferenceMaterialValueID { get; set; }
        public int ReferenceMaterialID { get; set; }
        public double ReferenceMaterialValue1 { get; set; }
        public Nullable<double> ReferenceMaterialAccuracy { get; set; }
        public int VariableID { get; set; }
        public int UnitsID { get; set; }
        public int CitationID { get; set; }
    
        public virtual Citation Citation { get; set; }
        public virtual ReferenceMaterial ReferenceMaterial { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Variable Variable { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
