//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedCitation
    {
        public int RelationID { get; set; }
        public int CitationID { get; set; }
        public int RelationshipTypeCV { get; set; }
        public int RelatedCitationID { get; set; }
    
        public virtual Citation Citation { get; set; }
        public virtual Citation Citation1 { get; set; }
    }
}
