//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedModel
    {
        public int RelatedID { get; set; }
        public int ModelID { get; set; }
        public string RelationshipTypeCV { get; set; }
        public int RelatedModelID { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
