//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedResult
    {
        public int RelationID { get; set; }
        public long ResultID { get; set; }
        public string RelationshipTypeCV { get; set; }
        public long RelatedResultID { get; set; }
        public string VersionCode { get; set; }
        public Nullable<int> RelatedResultSequenceNumber { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Result Result1 { get; set; }
    }
}
