//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedFeature
    {
        public int RelationID { get; set; }
        public int SamplingFeatureID { get; set; }
        public string RelationshipTypeCV { get; set; }
        public int RelatedFeatureID { get; set; }
        public Nullable<int> SpatialOffsetID { get; set; }
    
        public virtual SamplingFeature SamplingFeature { get; set; }
        public virtual SamplingFeature SamplingFeature1 { get; set; }
        public virtual SpatialOffset SpatialOffset { get; set; }
    }
}
