//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedAction
    {
        public int RelationID { get; set; }
        public int ActionID { get; set; }
        public string RelationshipTypeCV { get; set; }
        public int RelatedActionID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Action Action1 { get; set; }
    }
}
