//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedDataset
    {
        public int RelationID { get; set; }
        public int DataSetID { get; set; }
        public string RelationshipTypeCV { get; set; }
        public int RelatedDatasetID { get; set; }
        public string VersionCode { get; set; }
    
        public virtual DataSet DataSet { get; set; }
        public virtual DataSet DataSet1 { get; set; }
    }
}
