//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultTypeCV
    {
        public ResultTypeCV()
        {
            this.Results = new HashSet<Result>();
        }
    
        public string ResultTypeCV1 { get; set; }
        public string ResultTypeCategory { get; set; }
        public string DataType { get; set; }
        public string ResultTypeDefinition { get; set; }
        public string FixedDimensions { get; set; }
        public string VaryingDimensions { get; set; }
        public string SpaceMeasurementFramework { get; set; }
        public string TimeMeasurementFramework { get; set; }
        public string VariableMeasurementFramework { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
    }
}
