//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplingFeature
    {
        public SamplingFeature()
        {
            this.FeatureActions = new HashSet<FeatureAction>();
            this.ReferenceMaterials = new HashSet<ReferenceMaterial>();
            this.RelatedFeatures = new HashSet<RelatedFeature>();
            this.RelatedFeatures1 = new HashSet<RelatedFeature>();
            this.SamplingFeatureAnnotations = new HashSet<SamplingFeatureAnnotation>();
            this.SamplingFeatureExtensionPropertyValues = new HashSet<SamplingFeatureExtensionPropertyValue>();
            this.SamplingFeatureExternalIdentifiers = new HashSet<SamplingFeatureExternalIdentifier>();
        }
    
        public int SamplingFeatureID { get; set; }
        public System.Guid SamplingFeatureUUID { get; set; }
        public string SamplingFeatureTypeCV { get; set; }
        public string SamplingFeatureCode { get; set; }
        public string SamplingFeatureName { get; set; }
        public string SamplingFeatureDescription { get; set; }
        public string SamplingFeatureGeotypeCV { get; set; }
        public System.Data.Entity.Spatial.DbGeometry FeatureGeometry { get; set; }
        public Nullable<double> Elevation_m { get; set; }
        public string ElevationDatumCV { get; set; }
    
        public virtual ICollection<FeatureAction> FeatureActions { get; set; }
        public virtual ICollection<ReferenceMaterial> ReferenceMaterials { get; set; }
        public virtual ICollection<RelatedFeature> RelatedFeatures { get; set; }
        public virtual ICollection<RelatedFeature> RelatedFeatures1 { get; set; }
        public virtual ICollection<SamplingFeatureAnnotation> SamplingFeatureAnnotations { get; set; }
        public virtual ICollection<SamplingFeatureExtensionPropertyValue> SamplingFeatureExtensionPropertyValues { get; set; }
        public virtual ICollection<SamplingFeatureExternalIdentifier> SamplingFeatureExternalIdentifiers { get; set; }
        public virtual Site Site { get; set; }
        public virtual Specimen Specimen { get; set; }
    }
}
