//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionResultValue
    {
        public SectionResultValue()
        {
            this.SectionResultValueAnnotations = new HashSet<SectionResultValueAnnotation>();
        }
    
        public long ValueID { get; set; }
        public long ResultID { get; set; }
        public double DataValue { get; set; }
        public long ValueDateTime { get; set; }
        public long ValueDateTimeUTCOffset { get; set; }
        public double XLocation { get; set; }
        public double XAggregationInterval { get; set; }
        public int XLocationUnitsID { get; set; }
        public long ZLocation { get; set; }
        public double ZAggregationInterval { get; set; }
        public int ZLocationUnitsID { get; set; }
        public string CensorCodeCV { get; set; }
        public string QualityCodeCV { get; set; }
        public string AggregationStatisticCV { get; set; }
        public double TimeAggregationInterval { get; set; }
        public int TimeAggregationIntervalUnitsID { get; set; }
    
        public virtual SectionResult SectionResult { get; set; }
        public virtual ICollection<SectionResultValueAnnotation> SectionResultValueAnnotations { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
    }
}
