//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulation
    {
        public int SimulationID { get; set; }
        public int ActionID { get; set; }
        public string SimulationName { get; set; }
        public string SimulationDescription { get; set; }
        public System.DateTime SimulationStartDateTime { get; set; }
        public int SimulationStartDateTimeUTCOffset { get; set; }
        public System.DateTime SimulationEndDateTime { get; set; }
        public int SimulationEndDateTimeUTCOffset { get; set; }
        public double TimeStepValue { get; set; }
        public int TimeStepUnitsID { get; set; }
        public Nullable<int> InputDataSetID { get; set; }
        public int ModelID { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Model Model { get; set; }
    }
}
