//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int SamplingFeatureID { get; set; }
        public string SiteTypeCV { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int LatLonDatumID { get; set; }
    
        public virtual SamplingFeature SamplingFeature { get; set; }
        public virtual SpatialReference SpatialReference { get; set; }
    }
}
