//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpatialOffset
    {
        public SpatialOffset()
        {
            this.RelatedFeatures = new HashSet<RelatedFeature>();
        }
    
        public int SpatialOffsetID { get; set; }
        public string SpatialOffsetTypeCV { get; set; }
        public double Offset1Value { get; set; }
        public int Offset1UnitID { get; set; }
        public Nullable<double> Offset2Value { get; set; }
        public Nullable<int> Offset2UnitID { get; set; }
        public Nullable<double> Offset3Value { get; set; }
        public Nullable<int> Offset3UnitID { get; set; }
    
        public virtual ICollection<RelatedFeature> RelatedFeatures { get; set; }
    }
}
