//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpatialReference
    {
        public SpatialReference()
        {
            this.CategoricalResults = new HashSet<CategoricalResult>();
            this.MeasurementResults = new HashSet<MeasurementResult>();
            this.PointCoverageResults = new HashSet<PointCoverageResult>();
            this.ProfileResults = new HashSet<ProfileResult>();
            this.SectionResults = new HashSet<SectionResult>();
            this.Sites = new HashSet<Site>();
            this.SpatialReferenceExternalIdentifiers = new HashSet<SpatialReferenceExternalIdentifier>();
            this.SpectraResults = new HashSet<SpectraResult>();
            this.TimeSeriesResults = new HashSet<TimeSeriesResult>();
            this.TrajectoryResults = new HashSet<TrajectoryResult>();
            this.TransectResults = new HashSet<TransectResult>();
        }
    
        public int SpatialReferenceID { get; set; }
        public string SRSCode { get; set; }
        public string SRSName { get; set; }
        public string SRSDescription { get; set; }
    
        public virtual ICollection<CategoricalResult> CategoricalResults { get; set; }
        public virtual ICollection<MeasurementResult> MeasurementResults { get; set; }
        public virtual ICollection<PointCoverageResult> PointCoverageResults { get; set; }
        public virtual ICollection<ProfileResult> ProfileResults { get; set; }
        public virtual ICollection<SectionResult> SectionResults { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<SpatialReferenceExternalIdentifier> SpatialReferenceExternalIdentifiers { get; set; }
        public virtual ICollection<SpectraResult> SpectraResults { get; set; }
        public virtual ICollection<TimeSeriesResult> TimeSeriesResults { get; set; }
        public virtual ICollection<TrajectoryResult> TrajectoryResults { get; set; }
        public virtual ICollection<TransectResult> TransectResults { get; set; }
    }
}
