//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpectraResultValue
    {
        public SpectraResultValue()
        {
            this.SpectraResultValueAnnotations = new HashSet<SpectraResultValueAnnotation>();
        }
    
        public long ValueID { get; set; }
        public long ResultID { get; set; }
        public double DataValue { get; set; }
        public System.DateTime ValueDateTime { get; set; }
        public int ValueDateTimeUTCOffset { get; set; }
        public double ExcitationWavelength { get; set; }
        public double EmissionWavelength { get; set; }
        public int WavelengthUnitsID { get; set; }
        public string CensorCodeCV { get; set; }
        public string QualityCodeCV { get; set; }
        public double TimeAggregationInterval { get; set; }
        public int TimeAggregationIntervalUnitsID { get; set; }
    
        public virtual SpectraResult SpectraResult { get; set; }
        public virtual ICollection<SpectraResultValueAnnotation> SpectraResultValueAnnotations { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
