//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecimenTaxonomicClassifier
    {
        public int BridgeID { get; set; }
        public int SamplingFeatureID { get; set; }
        public int TaxonomicClassifierID { get; set; }
        public Nullable<int> CitationID { get; set; }
    
        public virtual Specimen Specimen { get; set; }
        public virtual TaxonomicClassifier TaxonomicClassifier { get; set; }
    }
}
