//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecimenBatchPostion
    {
        public int FeatureActionID { get; set; }
        public int BatchPositionNumber { get; set; }
        public string BatchPositionLabel { get; set; }
    
        public virtual FeatureAction FeatureAction { get; set; }
    }
}
