//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specimen
    {
        public Specimen()
        {
            this.SpecimenTaxonomicClassifiers = new HashSet<SpecimenTaxonomicClassifier>();
        }
    
        public int SamplingFeatureID { get; set; }
        public string SpecimenTypeCV { get; set; }
        public string SpecimenMediumCV { get; set; }
        public bool IsFieldSpecimen { get; set; }
    
        public virtual SamplingFeature SamplingFeature { get; set; }
        public virtual ICollection<SpecimenTaxonomicClassifier> SpecimenTaxonomicClassifiers { get; set; }
    }
}
