//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomicClassifier
    {
        public TaxonomicClassifier()
        {
            this.Results = new HashSet<Result>();
            this.SpecimenTaxonomicClassifiers = new HashSet<SpecimenTaxonomicClassifier>();
            this.TaxonomicClassifierExternalIdentifiers = new HashSet<TaxonomicClassifierExternalIdentifier>();
            this.TaxonomicClassifiers1 = new HashSet<TaxonomicClassifier>();
        }
    
        public int TaxonomicClassifierID { get; set; }
        public string TaxonomicClassifierTypeCV { get; set; }
        public string TaxonomicClassifierName { get; set; }
        public string TaxonomicClassifierCommonName { get; set; }
        public string TaxonomicClassifierDescription { get; set; }
        public Nullable<int> ParentTaxonomicClassifierID { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<SpecimenTaxonomicClassifier> SpecimenTaxonomicClassifiers { get; set; }
        public virtual ICollection<TaxonomicClassifierExternalIdentifier> TaxonomicClassifierExternalIdentifiers { get; set; }
        public virtual ICollection<TaxonomicClassifier> TaxonomicClassifiers1 { get; set; }
        public virtual TaxonomicClassifier TaxonomicClassifier1 { get; set; }
    }
}
