//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSeriesResultValue
    {
        public TimeSeriesResultValue()
        {
            this.TimeSeriesResultValueAnnotations = new HashSet<TimeSeriesResultValueAnnotation>();
        }
    
        public long ValueID { get; set; }
        public long ResultID { get; set; }
        public double DataValue { get; set; }
        public System.DateTime ValueDateTime { get; set; }
        public int ValueDateTimeUTCOffset { get; set; }
        public string CensorCodeCV { get; set; }
        public string QualityCodeCV { get; set; }
        public double TimeAggregationInterval { get; set; }
        public int TimeAggregationIntervalUnitsID { get; set; }
    
        public virtual TimeSeriesResult TimeSeriesResult { get; set; }
        public virtual ICollection<TimeSeriesResultValueAnnotation> TimeSeriesResultValueAnnotations { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
