//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.DataloggerFileColumns = new HashSet<DataloggerFileColumn>();
            this.DataloggerFileColumns1 = new HashSet<DataloggerFileColumn>();
            this.DataQualities = new HashSet<DataQuality>();
            this.ExtensionProperties = new HashSet<ExtensionProperty>();
            this.InstrumentOutputVariables = new HashSet<InstrumentOutputVariable>();
            this.MeasurementResults = new HashSet<MeasurementResult>();
            this.MeasurementResults1 = new HashSet<MeasurementResult>();
            this.MeasurementResults2 = new HashSet<MeasurementResult>();
            this.MeasurementResults3 = new HashSet<MeasurementResult>();
            this.PointCoverageResults = new HashSet<PointCoverageResult>();
            this.PointCoverageResults1 = new HashSet<PointCoverageResult>();
            this.PointCoverageResults2 = new HashSet<PointCoverageResult>();
            this.PointCoverageResultValues = new HashSet<PointCoverageResultValue>();
            this.PointCoverageResultValues1 = new HashSet<PointCoverageResultValue>();
            this.ProfileResults = new HashSet<ProfileResult>();
            this.ProfileResults1 = new HashSet<ProfileResult>();
            this.ProfileResults2 = new HashSet<ProfileResult>();
            this.ProfileResults3 = new HashSet<ProfileResult>();
            this.ProfileResultValues = new HashSet<ProfileResultValue>();
            this.ProfileResultValues1 = new HashSet<ProfileResultValue>();
            this.ReferenceMaterialValues = new HashSet<ReferenceMaterialValue>();
            this.Results = new HashSet<Result>();
            this.SectionResults = new HashSet<SectionResult>();
            this.SectionResults1 = new HashSet<SectionResult>();
            this.SectionResults2 = new HashSet<SectionResult>();
            this.SectionResults3 = new HashSet<SectionResult>();
            this.SectionResultValues = new HashSet<SectionResultValue>();
            this.SectionResultValues1 = new HashSet<SectionResultValue>();
            this.SectionResultValues2 = new HashSet<SectionResultValue>();
            this.SpectraResults = new HashSet<SpectraResult>();
            this.SpectraResults1 = new HashSet<SpectraResult>();
            this.SpectraResults2 = new HashSet<SpectraResult>();
            this.SpectraResults3 = new HashSet<SpectraResult>();
            this.SpectraResultValues = new HashSet<SpectraResultValue>();
            this.SpectraResultValues1 = new HashSet<SpectraResultValue>();
            this.TimeSeriesResults = new HashSet<TimeSeriesResult>();
            this.TimeSeriesResults1 = new HashSet<TimeSeriesResult>();
            this.TimeSeriesResults2 = new HashSet<TimeSeriesResult>();
            this.TimeSeriesResults3 = new HashSet<TimeSeriesResult>();
            this.TimeSeriesResultValues = new HashSet<TimeSeriesResultValue>();
            this.TrajectoryResults = new HashSet<TrajectoryResult>();
            this.TrajectoryResults1 = new HashSet<TrajectoryResult>();
            this.TrajectoryResultValues = new HashSet<TrajectoryResultValue>();
            this.TrajectoryResultValues1 = new HashSet<TrajectoryResultValue>();
            this.TrajectoryResultValues2 = new HashSet<TrajectoryResultValue>();
            this.TrajectoryResultValues3 = new HashSet<TrajectoryResultValue>();
            this.TransectResults = new HashSet<TransectResult>();
            this.TransectResults1 = new HashSet<TransectResult>();
            this.TransectResults2 = new HashSet<TransectResult>();
        }
    
        public int UnitsID { get; set; }
        public string UnitsTypeCV { get; set; }
        public string UnitsAbbreviation { get; set; }
        public string UnitsName { get; set; }
    
        public virtual ICollection<DataloggerFileColumn> DataloggerFileColumns { get; set; }
        public virtual ICollection<DataloggerFileColumn> DataloggerFileColumns1 { get; set; }
        public virtual ICollection<DataQuality> DataQualities { get; set; }
        public virtual ICollection<ExtensionProperty> ExtensionProperties { get; set; }
        public virtual ICollection<InstrumentOutputVariable> InstrumentOutputVariables { get; set; }
        public virtual ICollection<MeasurementResult> MeasurementResults { get; set; }
        public virtual ICollection<MeasurementResult> MeasurementResults1 { get; set; }
        public virtual ICollection<MeasurementResult> MeasurementResults2 { get; set; }
        public virtual ICollection<MeasurementResult> MeasurementResults3 { get; set; }
        public virtual ICollection<PointCoverageResult> PointCoverageResults { get; set; }
        public virtual ICollection<PointCoverageResult> PointCoverageResults1 { get; set; }
        public virtual ICollection<PointCoverageResult> PointCoverageResults2 { get; set; }
        public virtual ICollection<PointCoverageResultValue> PointCoverageResultValues { get; set; }
        public virtual ICollection<PointCoverageResultValue> PointCoverageResultValues1 { get; set; }
        public virtual ICollection<ProfileResult> ProfileResults { get; set; }
        public virtual ICollection<ProfileResult> ProfileResults1 { get; set; }
        public virtual ICollection<ProfileResult> ProfileResults2 { get; set; }
        public virtual ICollection<ProfileResult> ProfileResults3 { get; set; }
        public virtual ICollection<ProfileResultValue> ProfileResultValues { get; set; }
        public virtual ICollection<ProfileResultValue> ProfileResultValues1 { get; set; }
        public virtual ICollection<ReferenceMaterialValue> ReferenceMaterialValues { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<SectionResult> SectionResults { get; set; }
        public virtual ICollection<SectionResult> SectionResults1 { get; set; }
        public virtual ICollection<SectionResult> SectionResults2 { get; set; }
        public virtual ICollection<SectionResult> SectionResults3 { get; set; }
        public virtual ICollection<SectionResultValue> SectionResultValues { get; set; }
        public virtual ICollection<SectionResultValue> SectionResultValues1 { get; set; }
        public virtual ICollection<SectionResultValue> SectionResultValues2 { get; set; }
        public virtual ICollection<SpectraResult> SpectraResults { get; set; }
        public virtual ICollection<SpectraResult> SpectraResults1 { get; set; }
        public virtual ICollection<SpectraResult> SpectraResults2 { get; set; }
        public virtual ICollection<SpectraResult> SpectraResults3 { get; set; }
        public virtual ICollection<SpectraResultValue> SpectraResultValues { get; set; }
        public virtual ICollection<SpectraResultValue> SpectraResultValues1 { get; set; }
        public virtual ICollection<TimeSeriesResult> TimeSeriesResults { get; set; }
        public virtual ICollection<TimeSeriesResult> TimeSeriesResults1 { get; set; }
        public virtual ICollection<TimeSeriesResult> TimeSeriesResults2 { get; set; }
        public virtual ICollection<TimeSeriesResult> TimeSeriesResults3 { get; set; }
        public virtual ICollection<TimeSeriesResultValue> TimeSeriesResultValues { get; set; }
        public virtual ICollection<TrajectoryResult> TrajectoryResults { get; set; }
        public virtual ICollection<TrajectoryResult> TrajectoryResults1 { get; set; }
        public virtual ICollection<TrajectoryResultValue> TrajectoryResultValues { get; set; }
        public virtual ICollection<TrajectoryResultValue> TrajectoryResultValues1 { get; set; }
        public virtual ICollection<TrajectoryResultValue> TrajectoryResultValues2 { get; set; }
        public virtual ICollection<TrajectoryResultValue> TrajectoryResultValues3 { get; set; }
        public virtual ICollection<TransectResult> TransectResults { get; set; }
        public virtual ICollection<TransectResult> TransectResults1 { get; set; }
        public virtual ICollection<TransectResult> TransectResults2 { get; set; }
    }
}
