//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatfield.EnviroData.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public Variable()
        {
            this.InstrumentOutputVariables = new HashSet<InstrumentOutputVariable>();
            this.ReferenceMaterialValues = new HashSet<ReferenceMaterialValue>();
            this.Results = new HashSet<Result>();
            this.VariableExtensionPropertyValues = new HashSet<VariableExtensionPropertyValue>();
            this.VariableExternalIdentifiers = new HashSet<VariableExternalIdentifier>();
        }
    
        public int VariableID { get; set; }
        public string VariableTypeCV { get; set; }
        public string VariableCode { get; set; }
        public string VariableNameCV { get; set; }
        public string VariableDefinition { get; set; }
        public string SpeciationCV { get; set; }
        public double NoDataValue { get; set; }
    
        public virtual ICollection<InstrumentOutputVariable> InstrumentOutputVariables { get; set; }
        public virtual ICollection<ReferenceMaterialValue> ReferenceMaterialValues { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual ICollection<VariableExtensionPropertyValue> VariableExtensionPropertyValues { get; set; }
        public virtual ICollection<VariableExternalIdentifier> VariableExternalIdentifiers { get; set; }
    }
}
